name: SMotd
version: 1.0.0
api: [3.0.0, 3.1.0, 4.0.0]
author: solo
main: solo\smotd\SMotd
permissions:
  smotd:
    default: op
    children:
      smotd.command:
        default: op
        children:
          smotd.command.add:
            default: op
          smotd.command.interval:
            default: op
          smotd.command.list:
            default: op
          smotd.command.remove:
            default: op
